<a href="https://colab.research.google.com/github/osugizmo/collaboratory-link-01/blob/master/step1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [2]:
from scipy import sparse

# 対角成分が１でそれ以外が０の２次元のNumPy配列を作る
eye = np.eye(4)
print("NumPy array:\n{}".format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# NumPy配列をSciPyのCSR形式の疎行列に変換する(非ゼロ要素だけが格納される)
sparse_matrix = sparse.csc_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [13]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
print("\ndata:\n{}".format(data))
print("\nrow\n{}".format(row_indices))
print("\ncol\n{}".format(col_indices))
eye_coo = sparse.coo.matrix((data, (row_indices, col_indices)))
print("\nCOO representation:\n{}".format(eye_coo))


data:
[1. 1. 1. 1.]

row
[0 1 2 3]

col
[0 1 2 3]

COO representation:
[[array([[1.],
       [1.],
       [1.],
       [1.]])
  (array([0, 1, 2, 3]), array([0, 1, 2, 3]))]]
